version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: timetable_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: timetable_system
      MYSQL_USER: timetable_user
      MYSQL_PASSWORD: timetable_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - timetable_network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: timetable_backend
    ports:
      - "8080:8080"
    environment:
      # 修正: mariadbサービス名に変更
      DATABASE_URL: "root:password@tcp(mariadb:3306)/timetable_system?charset=utf8mb4&parseTime=True&loc=Local"
      DB_HOST: mariadb  # 修正: mysql → mariadb
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: timetable_system
      JWT_SECRET: "your-secret-key-change-this-in-production"
      PORT: "8080"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - timetable_network
    restart: unless-stopped

  # フロントエンドサービス
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: timetable_frontend
    environment:
      VITE_API_URL: "http://localhost:8080/api"
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - timetable_network
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  timetable_network:
    driver: bridge
