version: '3.8'

services:
  # データベース
  mariadb:
    image: mariadb:10.11
    container_name: timetable_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: timetable_system
      MARIADB_USER: timetable_user
      MARIADB_PASSWORD: timetable_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - timetable_network

  # バックエンド
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: timetable_backend
    environment:
      DATABASE_URL: "timetable_user:timetable_password@tcp(mariadb:3306)/timetable_system?charset=utf8mb4&parseTime=True&loc=Local"
      JWT_SECRET: "your-jwt-secret-key-for-testing"
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - timetable_network
    restart: unless-stopped

  # フロントエンド
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: timetable_frontend
    environment:
      VITE_API_URL: "http://localhost:8080/api"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - timetable_network
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  timetable_network:
    driver: bridge
